// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCYYUALHbS-GbyfIrlIit885ErOQUGuPk',
    appId: '1:606856715256:web:569c8c34ef65147970940d',
    messagingSenderId: '606856715256',
    projectId: 'flutter-news-app-391ac',
    authDomain: 'flutter-news-app-391ac.firebaseapp.com',
    storageBucket: 'flutter-news-app-391ac.appspot.com',
    measurementId: 'G-NM4TTG24WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7pFQTyRkhBYg9sDy6Ukb9Qt_Iab6PVYk',
    appId: '1:606856715256:android:8e28edf0dccfd43070940d',
    messagingSenderId: '606856715256',
    projectId: 'flutter-news-app-391ac',
    storageBucket: 'flutter-news-app-391ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyZ5_ysnyZHxZeIF-vuJongH0PHjHSr9E',
    appId: '1:606856715256:ios:4b31434544cb311170940d',
    messagingSenderId: '606856715256',
    projectId: 'flutter-news-app-391ac',
    storageBucket: 'flutter-news-app-391ac.appspot.com',
    iosClientId: '606856715256-qvkd1c5jg4q5ub7c5no0k0i7pde49s9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyZ5_ysnyZHxZeIF-vuJongH0PHjHSr9E',
    appId: '1:606856715256:ios:f90b0d1da688d7df70940d',
    messagingSenderId: '606856715256',
    projectId: 'flutter-news-app-391ac',
    storageBucket: 'flutter-news-app-391ac.appspot.com',
    iosClientId: '606856715256-i5ufs58h19gb4j0nq8sl7li01soh1lg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
